services:
  db:
    image: postgres:16-alpine
    container_name: salt2-ops-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integrated_ops_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
